export const BOOKS = [
  "A book with more than 500 pages",
  "A classic romance",
  "A book that became a movie",
  "A book published this year",
  "A book with a number in the title",
  "A book written by someone under 30",
  "A book with nonhuman characters",
  "A funny book",
  "A book by a female author",
  "A mystery or thriller",
  "A book with a one-word title",
  "A book of short stories",
  "A book set in a different country",
  "A nonfiction book",
  "A popular author's ﬁrst book",
  "A book from an author you love that you haven't read yet",
  "A book a friend recommended",
  "A Pulitzer Prize-winning book",
  "A book based on a true story",
  "A book at the bottom of your to-read list",
  "A book your mom loves",
  "A book that scares you",
  "A book more than 100 years old",
  "A book based entirely on its cover",
  "A book you were supposed to read in school but didn't",
  "A memoir",
  "A book you can ﬁnish in a day",
  "A book with antonyms in the title",
  "A book set somewhere you've always wanted to visit",
  "A book that came out the year you were born",
  "A book with bad reviews",
  "A trilogy",
  "A book from your childhood",
  "A book with a love triangle",
  "A book set in the future",
  "A book set in high school",
  "A book with a color in the title",
  "A book that made you cry",
  "A book with magic",
  "A graphic novel",
  "A book by an author you've never read before",
  "A book you own but have never read",
  "A book that takes place in your hometown",
  "A book that was originally written in a different language",
  "A book set during Christmas",
  "A book written by an author with your same initials",
  "A play",
  "A banned book",
  "A book based on or turned into a TV show",
  "A book you started but never finished",
];
